### PR TITLE
Remove jQuery from DataView

### PR DESCRIPTION
**Pull request by turnertime**
- enable unit testing of dataview in web-grid
- replace jQuery.extend with [node.extend](https://github.com/dreamerslab/node.extend)
- replace grep with [Array.Filter](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)

### CODE REVIEW

**Comment by turnertime** [comment]
Please note. I chose `node.extend` because I didn't want to rock the boat and instead have a library that is close to jQuery.extend. Also I only changed the modules that I needed to unit test web-grid.

**Comment by turnertime** [comment]
@pandell/core-developers Please review.

You can test this using [web-grid : remove-integration](https://github.com/pandell/web-grid/tree/remove-integration) branch.

**Comment by milang** [comment]
I like it, :+1: from me.

(@pandell/core-developers I recommend diffing with ignored whitespace to see actual changes).

**Comment by jgoz** [comment]
:+1: from me too.

**Comment by timphillips** [comment]
Nice change. :+1:

**Comment by 101100** [comment]
Looks good to me.  :cookie: 

Will this become a public npm package?

@milang Thanks for the tip RE: whitespace.

**Comment by turnertime** [comment]
@101100 No I think this will become `2.1.1-pandell.4` on npm.pandell registry.

**Comment by turnertime** [comment]
@pandell/core-developers Any objections to publishing as `2.1.1-pandell.4`?

**Comment by milang** [comment]
> Any objections to publishing as 2.1.1-pandell.4?

Fine by me (I assume we are already using exact dependency version spec).

**Comment by turnertime** [comment]
@milang Ok, I will release shortly. we are currently using `^2.1.1-pandell.3`. Should we remove the `^` for the exact version?

**Comment by jgoz** [comment]
@turnertime 

> Should we remove the ^ for the exact version?

I could go either way. The only reason to drop the `^` and pin an exact version is if we plan to do breaking changes on the `2.1.1-pandell.X` version, since we're not really following semver on this anyway.

**Comment by milang** [comment]
> Should we remove the ^ for the exact version?

semver

Considering these are work-in-progress releases, I prefer the non-`^` behaviour.

**Pull request merged**
