### PR TITLE
jQuery dependency

### PR DESCRIPTION
**Pull request by jgoz**
This adds `jquery` as an explicit dependency and uses `require` to load it wherever it is needed. This avoids any dependency on a global `jQuery` object and makes bundles more resilient to module load order.

After pandell/web-pli#181 was merged, it was revealed that `jquery-migrate` was polluting the global namespace with a `jQuery` instance that many slickgrid plugins were depending on. This makes those dependencies explicit.

(Any other visible changes are purely whitespace).

### CODE REVIEW

**Comment by jgoz** [comment]
@pandell/core-developers Please review.

**Comment by vicero** [comment]
Tested on SamplePliWeb and it works.  :+1:

**Comment by turnertime** [comment]
@jgoz Looks good to me, do we still need the function closures around each?

**Comment by jgoz** [comment]
@turnertime We could probably get rid of them, yeah. I'll see if I can do it in a mass find/replace way.

**Comment by jgoz** [comment]
@vicero, @turnertime Lots of whitespace related changes due to the last commit. I recommend viewing like this: https://github.com/pandell/SlickGrid/pull/8/files?w=1

**Comment by vicero** [comment]
@jgoz Retested and nothing seems broken to me :+1:

**Comment by 101100** [comment]
Code looks good to me.  :cookie:

**Pull request merged**
